"""empty message

Revision ID: 22f26252cdd7
Revises: ddbad6591bff
Create Date: 2020-09-11 08:36:05.103752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f26252cdd7'
down_revision = 'ddbad6591bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'name')
    # ### end Alembic commands ###
